use std::fmt::Display;

use nix::errno::Errno;

/// Error type for errors generated by Hopper
#[derive(Debug)]
pub enum Error {
    /// Hopper path was not specified or not found in the environment
    HopperNotFound,
    /// The specified [`crate::PipeMode`] was not valid
    InvalidMode,
    /// Pipe has not been opened yet
    NotOpen,
    /// I/O error
    Io(std::io::Error),
    /// Error specified by Unix error number
    Other(Errno),
}

impl std::error::Error for Error {}

impl Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::HopperNotFound => write!(
                f,
                "Hopper path not found and not specified, did you set HOPPER_PATH?"
            ),
            Self::InvalidMode => write!(f, "Specified pipe mode was not valid"),
            Self::NotOpen => write!(f, "Pipe is not open"),
            Self::Io(e) => write!(f, "I/O error: {e}"),
            Self::Other(e) => write!(f, "Hopper error: {e}"),
        }
    }
}

